### ISSUE TITLE
Simplify hello-world without confidential loading

### ISSUE THREAD

**Issue by jovanbulck** [sancus-tee/sancus-examples#17]
As discussed with @fritzalder we should simplify hello-world and hello-library to be more minimal and without confidential loading (which is also not supported on Aion).

Current hello-world can be renamed to something like hello-conf or so

Fritz:

> I'd vote for renaming hello-world to confidential-sm and rewrite hellow-world to be simpler and use sancus enable only

**Comment by jovanbulck** [comment]
@fritzalder when aion-core is merged hello-conf can be simply excluded in the build matrix for aion-core:

https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-excluding-configurations-from-a-matrix

**Comment by fritzalder** [comment]
#21 adds a confidential-loading example. I'll mark this as resolved so that we only have the PR remaining
